// Generated by Wrangler on Mon Apr 15 2024 19:43:04 GMT+0930 (Australian Central Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
}
