name = "vote"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-02-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "vote"
database_id = "1857d08e-8d72-4815-a470-1633a299e8d5"
